version: '3.2'

services:
  web:
    build:
      context: .
      dockerfile: ./build/web/Dockerfile
    volumes:
      - ${WWW}:/var/www/html/
    depends_on:
      - php
    networks:
      - frontend
      - default

  php:
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
    volumes:
      - ${WWW}:/var/www/html/
    networks:
      - default
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME